2020-06-04T05:24:06,153384707+02:00

diff --git a/zdocopt b/zdocopt
--- a/zdocopt
+++ b/zdocopt
@@ -41,6 +41,30 @@ warn() {
     return 0
 }
 
+ok_varname() {
+    local H V
+    case "$1" in *[!A-Z0-9_]*|[0-9]*)
+        warn "${2:+$2: }Bad variable name '$1'"
+        return 1
+    esac
+    return 0
+}
+
+# Usage: VARNAME PREFIX STRING
+#
+# Prefix every line in STRING with PREFIX, return in VARNAME.
+prefix() {
+    local _VAR="$1" _PRE="$2" _ARG='' IFS='
+'                                              # intentional newline
+    ok_varname "$_VAR" prefix || return 1      # verify VARNAME
+    set -- $3                                  # intentionally unquoted
+    for _ARG in "$@"; do
+        shift
+        set "$@" "$_PRE$_ARG"
+    done
+    eval "$_VAR"="\$*"
+}
+
 # Usage: append VARNAME STRING
 #
 # Append STRING to VARNAME with a space inbetween (unless VARNAME is empty, in
@@ -93,6 +117,19 @@ match() {
     return 1
 }
 
+# Usage: eqvar VARNAME1 VARNAME2
+#
+# Returns true (0) if variables VARNAME1 and VARNAME2 have identical content,
+# otherwise return false (1).
+eqvar() {
+    ok_varname "$1" eqvar || return 1
+    ok_varname "$2" eqvar || return 1
+    local A B
+    getvar A "$1"
+    getvar B "$2"
+    [ "$A" = "$B" ]
+}
+
 # Usage: parse RULESVAR TOKENIZED
 #
 # Go through TOKENIZED and create finite-state machine rules suitable for
@@ -134,12 +171,14 @@ match() {
 # whether it's a [...] or (...) group.
 #
 
-# ELLIPSIS RULES
-# ==============
-# Ellipsis rules are extra rules built up during the processing of each group,
-# which are only inserted into the final ruleset if the group in question is
-# followed by '...'. They are the purple rules in the finite state machine
-# images, and they allow for repetition.
+# ELLIPSIS RULES (_ELL<$LVL>)
+# ===========================
+# Ellipsis rules are extra rules built up during the processing of each
+# parenthesis/bracket group, which are only inserted into the final ruleset if
+# the group in question is followed by '...' (if not used, then the ellipsis
+# rules are forgotten upon exiting the group). In the Finate State Automaton
+# images, these are the lines marked in purple (which allow for repetition of a
+# group).
 #
 # FINAL STATES
 # ============
@@ -163,7 +202,7 @@ parse() {
     _DEBUG_LEVEL=''
     local _STATE=0 _STATEMAX=0
     local _RULES='' _FINAL=''
-    local _GRPMAX=0 IN=0 _LVL=0                # stack counter
+    local _GRPMAX=0 _LVL=0 _IN=0               # group count + level, current group
     local _BEG0=0 _END0=0 _GRP0=0 TYPE0=''     # loop stacks
     # Loop over $@ while setting $A to current arg, and $NEXT to next arg.
     local I=0 A='' NEXT='' PREV=''
@@ -171,22 +210,22 @@ parse() {
         eval    A="\"\$$I\""                   # current arg
         eval NEXT="\"\$$(( I + 1 ))\""         #   next arg
         append _DEBUG_STATE "$_STATE $A" || return 1
-        append _DEBUG_GROUP "$IN $A"     || return 1
+        append _DEBUG_GROUP "$_IN $A"    || return 1
         append _DEBUG_LEVEL "$_LVL $A"   || return 1
         case "$A" in
             ['(['])                            # start parenthesis or bracket
-                incvar _LVL                    #   group level
-                incvar _GRPMAX                 #   group number
-                IN="$_GRPMAX"                  #   current group number
-                incvar _STATEMAX
-                local "_BEG$_LVL"="$_STATE"    #   set group start state
-                local "_END$_LVL"="$_STATEMAX" #   set group end state
-                local "_GRP$_LVL"="$_GRPMAX"   #   loop stack: group number stack
-                case "$A" in                   #   loop stack: group types
+                incvar _LVL                    #   level (paren depth)
+                incvar _GRPMAX                 #   group (paren number)
+                incvar _STATEMAX               #   state counter
+                _IN="$_GRPMAX"                 #   current group
+                local "_BEG$_LVL"="$_STATE"    #     stack: group start state
+                local "_END$_LVL"="$_STATEMAX" #     stack: group end state
+                local "_GRP$_LVL"="$_GRPMAX"   #     stack: group number
+                local "_ELL$_LVL"=""           #     stack: ellipsis rule
+                case "$A" in                   #     stack: group type
                     '(') local "TYPE$_LVL"=')' ;;
                     '[') local "TYPE$_LVL"=']' ;;
                 esac
-                #local "ELLIPSIS$IN"=""         #   clear ellipsis rules
                 ;;
             '|')                               # pipe
                 # FIXME: Should '||', '[|', '(|', '|]' and '|)' be allowed?
@@ -200,22 +239,22 @@ parse() {
             ['])'])                            # end bracket
                 local TYPE; getvar TYPE "TYPE$_LVL"
                 [ "$_LVL" -le 0    ] && warn "Too many '$A' in rule: $*" && return 1
-                [ "$A" != "$TYPE" ] && warn "Missing '$A' in rule (group $IN): $*" && return 1
+                [ "$A" != "$TYPE" ] && warn "Missing '$A' in rule (group $_IN): $*" && return 1
                 unset TYPE
 
                 #getvar _STATE "_END$_LVL"      #     return state to start bracket
 
                 # Apply ellipsis rules if followed by '...'.
                 if [ "$NEXT" = '...' ]; then
-                    local ELLIPSIS; getvar ELLIPSIS "ELLIPSIS$IN"
-                    local NEWRULES; prefix NEWRULES "$_STATE:" "$ELLIPSIS"
+                    local _ELL; getvar _ELL "_ELL$_LVL"
+                    local NEWRULES; prefix NEWRULES "$_STATE:" "$_ELL"
                     appendnl "_RULES" "$NEWRULES" || return 1
-                    unset ELLIPSIS NEWRULES
+                    unset _ELL NEWRULES
                 fi
                 # Pop off last element of 'stack's.
-                unset "_GRP$_LVL" "TYPE$_LVL" "_BEG$_LVL" "_END$_LVL"
+                unset "_GRP$_LVL" "TYPE$_LVL" "_BEG$_LVL" "_END$_LVL" "_ELL$_LVL"
                 decvar _LVL                    #   go down one level
-                getvar IN "_GRP$_LVL"          #   current group number
+                getvar _IN "_GRP$_LVL"         #   current group number
                 # FIXME: These lines not covered by test cases!! (necessary?)
                 case "$NEXT" in [')]'])
                     local "_END$_LVL"="$_STATE"
@@ -247,13 +286,14 @@ parse() {
                     appendnl _RULES "$_STATE:$A -> $_STATE" || return 1
                 fi
                 case "$PREV" in ['[(|'])       # add ellipsis rule
-                    local "ELLIPSIS$IN"
-                    appendnl "ELLIPSIS$IN" "$A -> $_STATE" || return 1
-
-                    # # go backward, add rules to previous nested states
-                    # local _I="$_LVL"
-                    
-                    # echo "LEVEL: $_LVL"
+                    appendnl "_ELL$_LVL" "$A -> $_STATE" || return 1
+                    # If this group and previous group start at same state (ie
+                    # leading parenthesis is doubled, tripled etc) then copy
+                    # ellipsis rules to previous group as well.
+                    local _J="$_LVL"
+                    while decvar _J && [ "$_J" -gt 0 ] && eqvar "_BEG$_LVL" "_BEG$_J"; do
+                        appendnl "_ELL$_J" "$A -> $_STATE" || return 1
+                    done
                 esac
                 ;;
         esac
@@ -270,9 +310,9 @@ parse() {
         #         _DEBUG_INDENT="${_DEBUG_INDENT#  }" ;;
         # esac
         # local TMP
-        # getvar TMP "ELLIPSIS$IN"
+        # getvar TMP "_ELL$_LVL"
         # out "${_DEBUG_INDENT}'$A'"
-        # out "${_DEBUG_INDENT}    ((ELLIPSIS$IN: $TMP))"
+        # out "${_DEBUG_INDENT}    ((ELLIPSIS$_LVL: $TMP))"
         # #out "  ${_DEBUG_INDENT}LVL:$_LVL STATE:$_STATE"
         # _DEBUG_INDENT="$_DEBUG_INDENT_NEXT"
         PREV="$A"
@@ -280,7 +320,7 @@ parse() {
     unset "_GRP0"  # last element of group stack
     unset "TYPE0"
     append _DEBUG_STATE "$_STATE" || return 1
-    append _DEBUG_GROUP "$IN"    || return 1
+    append _DEBUG_GROUP "$_IN"    || return 1
     append _DEBUG_LEVEL "$_LVL"   || return 1
 
     if [ "$_LVL" -ne 0 ]; then
@@ -289,30 +329,6 @@ parse() {
         return 1
     fi
     setvar "$_VAR" "$_RULES"
-}
-
-ok_varname() {
-    local H V
-    case "$1" in *[!A-Z0-9_]*|[0-9]*)
-        warn "${2:+$2: }Bad variable name '$1'"
-        return 1
-    esac
-    return 0
-}
-
-# Usage: VARNAME PREFIX STRING
-#
-# Prefix every line in STRING with PREFIX, return in VARNAME.
-prefix() {
-    local _VAR="$1" _PRE="$2" _ARG='' IFS='
-'                                              # intentional newline
-    ok_varname "$_VAR" prefix || return 1      # verify VARNAME
-    set -- $3                                  # intentionally unquoted
-    for _ARG in "$@"; do
-        shift
-        set "$@" "$_PRE$_ARG"
-    done
-    eval "$_VAR"="\$*"
 }
 
 ################################################################################
@@ -325,10 +341,21 @@ TESTS_DONE=''
 TMPDIR="$(mktemp -dt zdocpt2-XXXXXX)"
 TMPNUM="0"
 BIN="${0##*/}"
-trap "trap - EXIT INT
-     [ -d '$TMPDIR' ] && rm -r '$TMPDIR';
-     [ \"\$TESTS_DONE\" ] || out '***PREMATURE EXIT! Not all tests ran!';
-     exit" EXIT INT
+trap "trapfunc \"$TMPDIR\"" EXIT INT
+
+trapfunc() {
+    local TMPDIR="$1"
+    trap - EXIT INT
+    [ -d '$TMPDIR' ] && rm -r '$TMPDIR'
+    if [ -z "$TESTS_DONE" ]; then
+       out '***PREMATURE EXIT! Not all tests ran!'
+       printf '==============================================\n'
+       printf '== %-40s ==\n' 'ABORTED EXECUTION!!!!!!!!!!!!11111!!!'
+       printf '== %-40s ==\n' "Ran $TESTS_COUNT tests before exiting."
+       printf '==============================================\n'
+    fi
+    exit 15
+}
 
 # Usage: tmpfile VARNAME
 #
@@ -371,7 +398,7 @@ test() {
 
 done_testing() {
     TESTS_DONE=1
-    if [ "$FAILED_TESTS" -gt 0 ]; then
+    if [ "$FAILED_TESTS" -ne 0 ]; then
         printf '==============================================\n'
         printf '== %-40s ==\n' 'ERRORS!!!!!!!!!!!!11111!!!'
         printf '== %-40s ==\n' "$FAILED_TESTS (of $TESTS_COUNT) tests failed!"
@@ -414,37 +441,6 @@ readall() {
 ##  Tests                                                                     ##
 ##                                                                            ##
 ################################################################################
-
-# FIXME: Add test cases for 
-INPUT='  (   (   A   )   ...   B   )'
-INPUT='  (   (   A   )   ...   B   )   ...'
-INPUT='  (   (   A   )   B   )   ...'
-INPUT='  (   (   (   A   )   B   )   C   )   ...'
-INPUT='  (   (   (   A   )   ...   B   )   C   )   ...'
-
-INPUT='  (   A   ...   )   ...'          # Does this make sense?
-INPUT='  (   A   ...   |   B   )   ...'  # This does!
-
-
-# # FIXME: Since state '1' was eaten here, the last rule output
-# # FIXME: when we have a case of multiple endings ) )... we must update _END$_LVL for those groups
-# # FIXME: Implement rules here
-# INPUT='  (   (   A   )   B   )   ...'
-# LEVEL='0 ( 1 ( 2 A 2 ) 1 B 1 ) 0 ... 0'
-# GROUP='0 ( 1 ( 2 A 2 ) 1 B 1 ) 0 ... 0'
-# STATE='0 ( 0 ( 0 A 2 ) 2 B 1 ) 1 ... 1'; FINAL=1
-# RULES='0:A -> 2
-# 2:B -> 1
-# 1:A -> 2'
-# parse GOTTED_RULES $INPUT && :; RETVAL="$?"    # intentionally unquoted
-# test "$RETVAL"       '0'      'Return value'
-# test "$_DEBUG_LEVEL" "$LEVEL" "Bracket level: '$INPUT'"
-# test "$_DEBUG_GROUP" "$GROUP" "Group numbers: '$INPUT'"
-# test "$_DEBUG_STATE" "$STATE" "State numbers: '$INPUT'"
-# test "$GOTTED_RULES" "$RULES"         "Rules: '$INPUT'"
-
-# done_testing
-# exit
 
 ######################################################################
 ##
@@ -964,9 +960,20 @@ test "$_DEBUG_GROUP" "$GROUP" "Group numbers: '$INPUT'"
 test "$_DEBUG_STATE" "$STATE" "State numbers: '$INPUT'"
 test "$GOTTED_RULES" "$RULES"         "Rules: '$INPUT'"
 
+
+
+# FIXME: Add test cases for 
+INPUT='  (   (   A   )   ...   B   )'
+INPUT='  (   (   A   )   ...   B   )   ...'
+INPUT='  (   (   A   )   B   )   ...'
+INPUT='  (   (   (   A   )   B   )   C   )   ...'
+INPUT='  (   (   (   A   )   ...   B   )   C   )   ...'
+
+INPUT='  (   A   ...   )   ...'          # Does this make sense?
+INPUT='  (   A   ...   |   B   )   ...'  # This does!
+
 # FIXME: Since state '1' was eaten here, the last rule output
 # FIXME: when we have a case of multiple endings ) )... we must update _END$_LVL for those groups
-# FIXME: Implement rules here
 INPUT='  (   (   A   )   B   )   ...'
 LEVEL='0 ( 1 ( 2 A 2 ) 1 B 1 ) 0 ... 0'
 GROUP='0 ( 1 ( 2 A 2 ) 1 B 1 ) 0 ... 0'
@@ -979,7 +986,36 @@ test "$RETVAL"       '0'      'Return value'
 test "$_DEBUG_LEVEL" "$LEVEL" "Bracket level: '$INPUT'"
 test "$_DEBUG_GROUP" "$GROUP" "Group numbers: '$INPUT'"
 test "$_DEBUG_STATE" "$STATE" "State numbers: '$INPUT'"
-#test "$GOTTED_RULES" "$RULES"         "Rules: '$INPUT'"
+test "$GOTTED_RULES" "$RULES"         "Rules: '$INPUT'"
+
+INPUT='  (   (   A   )   ...   B   )'
+LEVEL='0 ( 1 ( 2 A 2 ) 1 ... 1 B 1 ) 0'
+GROUP='0 ( 1 ( 2 A 2 ) 1 ... 1 B 1 ) 0'
+STATE='0 ( 0 ( 0 A 2 ) 2 ... 2 B 1 ) 1'; FINAL=1
+RULES='0:A -> 2
+2:A -> 2
+2:B -> 1'
+parse GOTTED_RULES $INPUT && :; RETVAL="$?"    # intentionally unquoted
+test "$RETVAL"       '0'      'Return value'
+test "$_DEBUG_LEVEL" "$LEVEL" "Bracket level: '$INPUT'"
+test "$_DEBUG_GROUP" "$GROUP" "Group numbers: '$INPUT'"
+test "$_DEBUG_STATE" "$STATE" "State numbers: '$INPUT'"
+test "$GOTTED_RULES" "$RULES"         "Rules: '$INPUT'"
+
+INPUT='  (   (   A   )   ...   B   )   ...'
+LEVEL='0 ( 1 ( 2 A 2 ) 1 ... 1 B 1 ) 0 ... 0'
+GROUP='0 ( 1 ( 2 A 2 ) 1 ... 1 B 1 ) 0 ... 0'
+STATE='0 ( 0 ( 0 A 2 ) 2 ... 2 B 1 ) 1 ... 1'; FINAL=1
+RULES='0:A -> 2
+2:A -> 2
+2:B -> 1
+1:A -> 2'
+parse GOTTED_RULES $INPUT && :; RETVAL="$?"    # intentionally unquoted
+test "$RETVAL"       '0'      'Return value'
+test "$_DEBUG_LEVEL" "$LEVEL" "Bracket level: '$INPUT'"
+test "$_DEBUG_GROUP" "$GROUP" "Group numbers: '$INPUT'"
+test "$_DEBUG_STATE" "$STATE" "State numbers: '$INPUT'"
+test "$GOTTED_RULES" "$RULES"         "Rules: '$INPUT'"
 
 ######################################################################
 ##
